# Generated by Django 2.1.2 on 2018-10-08 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.UUIDField(default=uuid.uuid4)),
                ('account_name', models.TextField(max_length=100)),
                ('account_number', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=50)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(max_length=255)),
                ('value', models.TextField(max_length=500)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Account')),
            ],
            options={
                'verbose_name': 'AccountMeta',
                'verbose_name_plural': 'AccountMetas',
                'db_table': 'account_meta',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField()),
                ('debit', models.BigIntegerField()),
                ('credit', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('note', models.TextField(max_length=500)),
                ('status', models.TextField(max_length=50)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Account')),
            ],
            options={
                'verbose_name': 'AccountMeta',
                'verbose_name_plural': 'AccountMetas',
                'db_table': 'account_transaction',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('base_url', models.TextField(max_length=255)),
                ('scrapping_period', models.IntegerField()),
                ('status', models.TextField(max_length=50)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='SystemApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('api_key', models.TextField(max_length=255)),
                ('type', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=50)),
                ('ip', models.TextField(max_length=255, null=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SystemApp',
                'verbose_name_plural': 'SystemApps',
                'db_table': 'system_app',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(max_length=255)),
                ('value', models.TextField(max_length=500, null=True)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SystemConfig',
                'verbose_name_plural': 'SystemConfigs',
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='TransferAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.UUIDField()),
                ('amount', models.TextField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(max_length=50)),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TransferAmount',
                'verbose_name_plural': 'TransferAmounts',
                'db_table': 'transfer_amount',
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(max_length=50)),
                ('real_amount', models.BigIntegerField()),
                ('deleted', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Account')),
                ('transfer_amount_id', models.ForeignKey(default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.TransferAmount')),
            ],
            options={
                'verbose_name': 'TransferRequest',
                'verbose_name_plural': 'TransferRequest',
                'db_table': 'transfer_request',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank_id',
            field=models.ForeignKey(default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Bank'),
        ),
    ]
